name: bigcommerce_nuxt

# The language and version for your app.
type: 'nodejs:20'

# The size of the app's persistent disk (in MB).
disk: 2048

# The app's configuration when it's exposed to the web.
web:
    locations:
        '/':
            # The public directory relative to the app root.
            root: 'dist'
            # Forward resources to the app.
            passthru: true
            # What files to use when serving a directory.
            index: ["index.html"]
            # Allow files even without specified rules.
            allow: true